services:
  - type: web
    name: freya-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: freya-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://freya-frontend.onrender.com
      - key: CLICK_MERCHANT_ID
        value: your_click_merchant_id
      - key: CLICK_SERVICE_ID
        value: your_click_service_id
      - key: CLICK_SECRET_KEY
        value: your_click_secret_key
      - key: ESKIZ_EMAIL
        value: fayzullindmr@gmail.com
      - key: ESKIZ_PASSWORD
        value: rlPJjmkaqRvZshRoNpcIiCFtC5GiNzI7k7YNe8fs
      - key: ESKIZ_TOKEN
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjExMDgxNzMsImlhdCI6MTc1ODUxNjE3Mywicm9sZSI6InVzZXIiLCJzaWduIjoiY2Y0MjBjNzQ5ODQ0NjhkMjVlMDI2ODkyNTI1NTZlZTgzZTc5OWUxMjIxMzFiMGNlYTBkYzAxZmE4MTIxMjRkMyIsInN1YiI6IjExOTE5In0.x5GCzyXbo70ODY1WRWYJgMUN5qDWwaCYQI83lq7jXw0
      - key: ESKIZ_BASE_URL
        value: https://notify.eskiz.uz/api
      - key: UPLOAD_PATH
        value: uploads/
      - key: MAX_FILE_SIZE
        value: 5242880
    healthCheckPath: /api/health